Feature: Format feature files
   In order to ensure proper formatting of files generated by xmind
   As a feature worker, I want to format my files
   ddd
      fff
        fff
Scenario: Remove empty lines
Given abc

Scenario: Remove empty lines
